// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QualitySensorData.Data;

#nullable disable

namespace QualitySensorData.Migrations
{
    [DbContext(typeof(QualitySensorDbContext))]
    [Migration("20231023202448_InitialRun")]
    partial class InitialRun
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QualitySensorData.Model.QualitySensorDataMdl", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<int>("SensorID")
                        .HasColumnType("int");

                    b.Property<float>("clorin")
                        .HasColumnType("real");

                    b.Property<int>("co2")
                        .HasColumnType("int");

                    b.Property<int>("conductivity")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("floor")
                        .HasColumnType("int");

                    b.Property<int>("humidity")
                        .HasColumnType("int");

                    b.Property<int>("pH")
                        .HasColumnType("int");

                    b.Property<int>("temp")
                        .HasColumnType("int");

                    b.Property<int>("turbidity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("QualitySensorDataTable");
                });
#pragma warning restore 612, 618
        }
    }
}
