// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QualitySensorData.Data;

#nullable disable

namespace QualitySensorData.Migrations
{
    [DbContext(typeof(QualitySensorDbContext))]
    [Migration("20231027115248_ReadyAPI1.0")]
    partial class ReadyAPI10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QualitySensorData.Model.ConsumptionStat", b =>
                {
                    b.Property<long>("sensorid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("sensorid"));

                    b.Property<int>("consuption")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("sfloor")
                        .HasColumnType("int");

                    b.Property<string>("utilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sensorid");

                    b.ToTable("ConsumptionData");
                });

            modelBuilder.Entity("QualitySensorData.Model.FloorConsumption", b =>
                {
                    b.Property<int>("floor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("floor"));

                    b.Property<float>("consumptionOnFoor")
                        .HasColumnType("real");

                    b.Property<float>("consumptionPercent")
                        .HasColumnType("real");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("floor");

                    b.ToTable("floorWiseConsumptionData");
                });

            modelBuilder.Entity("QualitySensorData.Model.QualitySensorDataMdl", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<int>("SensorID")
                        .HasColumnType("int");

                    b.Property<float>("clorin")
                        .HasColumnType("real");

                    b.Property<int>("co2")
                        .HasColumnType("int");

                    b.Property<int>("conductivity")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("floor")
                        .HasColumnType("int");

                    b.Property<int>("humidity")
                        .HasColumnType("int");

                    b.Property<int>("pH")
                        .HasColumnType("int");

                    b.Property<int>("temp")
                        .HasColumnType("int");

                    b.Property<int>("turbidity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("QualitySensorDataTable");
                });
#pragma warning restore 612, 618
        }
    }
}
